var data = [
  {
    name: 'What Is Adware?',
    url: 'what-is-adware',
    description: `<h3>What Is Adware?</h3><p>Almost everyone deals with Adware now. Adware is a bit typical malware that keeps popping up every now and then. In simple words, Adware or advertising malware pops up undesired advertisement.<p>
It may seem like not that harmful but it can do an awful lot of damage to your system. In spite of being irritating, it weakens your security system and tracks your activities on the internet. This security breach further results in other malware attacks.
</p><h3>What does Adware do?</h3><p>Adware can act differently on computers. They are not as simple as they may seem. There are numerous ways an adware can take advantage of your system:</p>
<p><b>•	Pop-Ups:</b> Pop-Ups are really annoying and these are the typical form of an adware. If your computer is affected by adware you will get pop-ups more frequently.<p>
•	<b>Spying On Your System:</b>It also excels at spying on your system. Tracking all your online activity it seems to show you advertisement relevant to your searches.<p>
•	<b>A Mole in A Protected Connection:</b> Some Adware directs all your connections through their server. This includes protected connection as well. So, if you are connecting with your bank accounts all of the data might be in their system.<p>
•<b>	Makes Your Computer Run Slow:</b> They take up a lot of CPU spaces which ultimately slows down your PC.<p>•	<b>Sucks up Your Internet Data:</b>Adware sucks up your data every time they download advertisement or load another pop-up page. This can really affect your browsers too!
</p><h3>How Can You Get Rid of It?</h3><p>A solution to this problem would be to have an adware removal tool or anti-malware tool installed on your system. It will provide the necessary protection you need.<p>
You can also try out blocking scripts but it can also disable your web surfing as well. The best way would be to be careful when you download a file from unknown locations or avoid malicious websites.
</p>`
  },
  {
    name: 'What Is Phishing?',
    url: 'what-is-phishing',
    description: `<h3>What Is Phishing?</h3> <p>Today’s world is surrounded by maliciouscybercrimes. Phishing is one of them. In phishing, someone or some group targets people through phone calls, text messages or email disguising as a genuine institution.<p>Attackers use trustworthy electronic communication to attract individualsfor providing their important personal data such as credit card details, username,and passwords. They then use these pieces of information to steal identity or money or any valuable property. </p><h3>Types of phishing</h3><p><b>•Spear phishing</b><p>When specific companies or individuals become the direct target of phishing, they are called spear phishing. This type of phishing is most successful one on theinternet nowadays, around 91% of attacks are Spear phishing. <p> <b>•Clone phishing</b><p>Sometimes, some previously delivered legitimate emails contain any link or attachment which has its content and recipient address. Attackers hack them and use them to create cloned or almost identical email. Then they replaced that link or attachment with malevolent version and send it from such an email address which is spoofed to believe as theoriginal. Now, this type of phishing is known as clone phishing. <b>•Whaling</b><p>Another type of phishing is whaling. Senior executives and high-profile persons within businesses are the targets for this type of phishing attacks. <p>Most of the contents are written about any serious matter such as customer complaint or any legal issue.All of these are masqueraded so well that any superior person of a company is mentally forced to click those links or attachments. <p>Social engineering techniques are blessings of modern science. But phishing is a ridiculous example of misusing these techniques to deceive people.<p> Attackers use so many methods for phishing such as link manipulation, website forgery, covert redirect, phone phishing and so on.Public awareness, user training, technical security measures and legislation can help you to deal with the growing number of phishing. </p>`
  },
  {
    name: 'What is a Trojan Horse?',
    url: 'what-is-a-trojan-horse',
    description: `<h3>What is a Trojan Horse?</h3> <p>There are so many threats lurking around the internet nowadays. If you are not careful enough, you too can be a victim of this dreadful situation. <p>Trojan Horse is just another one of those threats that can truly harm your personal life along with your professional one. A Trojan Horse is a type of malware that comes as a normal file but steals your data once it gets ahold of your computer. <p>The scariest part is that they can go unnoticed for a really long time. This unique malware hides behind an ordinary file or program and creates holes in your security system leaking all of your precious data.</p><h3>How Do They Affect Your Computer?</h3><p>You won’t believe how a Trojan Horse can affect your computer. They can do some serious changes to your system: <p><p><b>•Create Loopholes In Your Security:</b> Trojans mainly create a backdoor for any hacker or other malware to get in. Your security system would be dead in a few days.><p><b>•Steal Your Information:</b> They are mainly one type of Spyware. These snoop into your personal data like credit card info or account password and send them to a third party.<p> <b>•Takes over The PC:</b> Sometimes cybercriminals use them to freeze your PC and shut you out entirely. <b>•Sends Email Or SMS:</b> Mobile devices are also affected by Trojans. Criminals usually send costly messages to specific numbers and hack out the money. <h3>Can You Know Which Files Are Trojan?</h3><p>They can look similar to any type of files. They can be mp3 files or PDF files or any other program. The worst part is that they would seem harmless and you won’t even notice anything when you install them or download them.<p>Some Trojans go to a whole another level and trick you into downloading them. Trojans are cyber criminal’s number one choice. That’s why you should always be careful or have a working Antivirus program on your PC. </p></p>`
  },
  {
    name: 'How Dangerous Is the Web Today',
    url: 'how-dangerous-is-the-web-today',
    description: `<h3>How Dangerous Is the Web Today</h3> <p>There is no doubt that internet is a wonderful tool for many of us. But from time to time we end up becoming a victim of the cyber-crimes. According to recent statistics over $2 trillion will get in the hands of cybercriminals by 2019. <p>Not even that, last year over 15.4 million people reported a case of identity theft. That’s a huge number to even begin with! So, even if you are a tech savvy you can still fall prey to these predators. </p><h3>What Are The Threats?</h3><p><b>•Flash Files: </b> Adobe flash’s flash cookies can track your process on the web just like other cookies. The worst part is that they remain even if you delete all your browsers cookies.<p> <b>•Shortened Links: </b> These are mainly Twitter links that scammers use to lure away a user to any malicious website. They can also be a Trojan Horse in disguise. <p><b>•Email Scammers: </b> One of the dangerous threats on the web. Scammers send users infected emails or attachments that can lead to information theft.<p><b>•Trojan Horse: </b> Sometimes different sites will tell you to download codec files of videos. Normally, thesesoftwares are legitimate for some reputed video sites. But not all of them are genuine. They can be Trojan Horse.<p> <b>•Poisoned Search Engines: </b> Poisonous search engines will track what you are searching and will get you pages or sites full of malevolent contents. Attackers make such kind of malware sites with high rank so that the sites have a higher ranking.<p><b>•Infected PDFs: </b>Attackers always find new ways to attack you. They can also attack you through pdf files including malevolent contents.<p><b>•Drive-By Downloads: </b>Some malware will get downloaded just when you click a link or open a site. These downloaded files are mostly malware.<p><b>•Scam Antiviruses: </b>Sometimes you may get anti-virus suggestions on theinternet,which are actually not the real software. But you can mix them up with actual anti-virus.This fake antivirus will damage your computer instead of protecting it. <p>All of these threats make our digital life a bit difficult. And, that’s why the perfect solution for this would be cyber security. </p>`
  },
  {
    name: 'How Important Is Cybersecurity In This Day And Age?',
    url: 'how-important-is-cybersecurity-in-this-day-and-age',
    description: `<h3>How Important Is Cybersecurity In This Day And Age?</h3> <p>The security or protections of computer systems from any kind of damage or theft to their information, software or hardware and also from misleading of the provided services refer to cybersecurity.<p> Cybersecurityprovides all kind of physical protection to the hardware system as well as to the network system, leaking data, hacking information and recoding the software. So, none can be tricked anymore through cybercrime.</p><h3>Cybercrime Is a Threat to Everyone</h3><p>We are surrounded by computer systems. Cyber system has touched every aspect of our life. Schools, colleges, universities, industries, small or large companies, shops, bank, government; all of them are computer-based. <p>A large portion of our life is stuck on the internet. It has become the most important part of our life. We all are connected to the cyber system somehow. And the attackers are taking advantages of our cyber system based life. </p>So, basically, without cybersecurity no one is safe and no information is safe. <p><b>Why Do You Need Cybersecurity?</b><p>Cyber attackers keep attacking us through messages, phone calls or emails with their malicious contents, links, web pages or images. They can attack you anytime by spoofing, phishing, eavesdropping, tampering, click-jacking, and direct-accessing and so on. <p>If your cybersecurity system is not activated, your computer can be hacked any moment and all your information as well. Attackers can thieve all the information from the website of any organization. <p>Even they can hack your personal information and use your identity for doing any crime. This identity theft can cause you a lot of personal and legal problem as well. You just click on an unknown link and all your information will be hacked easily. And without cybersecurity, it is not that tough to sendyou a message or email including malevolent link or images to hack your information or destroy your cyber system or hacking all your money from the bank.<p> In this day and age, the whole world depends on the computer-based systems. From a school to a large industry, every single organization and the modern educated person is related to the cyber system. Security comes first and cybersecurity is a must. </p>`
  },
]


export default data;
